# Generated by Django 3.2 on 2025-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier'),
        ),
    ]
