# Generated by Django 3.2 on 2025-02-25 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_supplier_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status_electronics',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
