# Generated by Django 3.2 on 2025-02-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20250225_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='last_name',
            new_name='company',
        ),
    ]
